# Generated by Django 5.0.6 on 2024-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_alter_dessert_calories_alter_dessert_freshness_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='subcategory',
        ),
    ]
